# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, help_text='Please enter age')),
                ('height', models.IntegerField(blank=True, help_text='Please enter height in cm.')),
                ('weight', models.IntegerField(blank=True, help_text='Please enter weight in kg')),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REG', 'Regular'), ('TRN', 'Trainer'), ('ADM', 'Admin')], default='REG', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='training_level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Expert')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Training_level_of_event', to='mainpage.Level'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='Participants_of_event', to='mainpage.Profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trainer_of_event', to='mainpage.Profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Training_level_of_user', to='mainpage.Level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_status', to='mainpage.UserStatus'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
