# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20161024_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='Participants_of_event', to='mainpage.Profile'),
        ),
    ]
