# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_auto_20161108_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='days',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='0', max_length=1),
        ),
    ]
