# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20161109_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], default='0', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='days',
        ),
        migrations.AddField(
            model_name='class',
            name='days',
            field=models.ManyToManyField(related_name='days_of_class', to='mainpage.Days'),
        ),
    ]
