# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_auto_20161110_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='name',
            field=models.CharField(default='Monday', max_length=10),
        ),
    ]
